default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: dev
  password: root
  port: 5432

development:
  <<: *default
  database: dev_db
  username: dev
  password: root

test:
  <<: *default
  database: test_db
  username: dev
  password: root

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
